openapi: 3.0.0
info:
  title: OAuth 2.0 Echo API
  description: "Illustrates \"Client Credentials\" OAuth 2.0 Grant Type. This grant type is used by clients to obtain an access token outside of the context of a user."
  version: "1.0"
paths:
  /token:
    get:
      summary: "Returns a new token to an authorized client"
      parameters: 
        - name: client_id
          in: header
          description: the client's id
          schema:
            type: string 
        - name: client_secret
          in: header
          description: the client's secret
          schema:
            type: string         
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/AccessToken'
        "401":
          description: unauthorized
  /echo:
    get:
      summary: "Returns a message sent by an authorized client"
      parameters:
      - name: msg
        in: query
        description: a message to be echoed
        schema:
          type: string
      - name: Authorization
        in: header
        description: the client's access token
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Message'
        "401":
          description: unauthorized
components:
  schemas:
    AccessToken:
      required:
      - access_token
      - expires_in
      - token_type
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        token_type:
          type: string
    Message:
      required:
      - msg
      type: object
      properties:
        msg:
          type: string